// Code generated by ent, DO NOT EDIT.

package receipt

import (
	"billing/internal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Receipt {
	return predicate.Receipt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Receipt {
	return predicate.Receipt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Receipt {
	return predicate.Receipt(sql.FieldLTE(FieldID, id))
}

// Retailer applies equality check predicate on the "retailer" field. It's identical to RetailerEQ.
func Retailer(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldRetailer, v))
}

// PurchaseDate applies equality check predicate on the "purchase_date" field. It's identical to PurchaseDateEQ.
func PurchaseDate(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldPurchaseDate, v))
}

// PurchaseTime applies equality check predicate on the "purchase_time" field. It's identical to PurchaseTimeEQ.
func PurchaseTime(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldPurchaseTime, v))
}

// Total applies equality check predicate on the "total" field. It's identical to TotalEQ.
func Total(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldTotal, v))
}

// RetailerEQ applies the EQ predicate on the "retailer" field.
func RetailerEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldRetailer, v))
}

// RetailerNEQ applies the NEQ predicate on the "retailer" field.
func RetailerNEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNEQ(FieldRetailer, v))
}

// RetailerIn applies the In predicate on the "retailer" field.
func RetailerIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldIn(FieldRetailer, vs...))
}

// RetailerNotIn applies the NotIn predicate on the "retailer" field.
func RetailerNotIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNotIn(FieldRetailer, vs...))
}

// RetailerGT applies the GT predicate on the "retailer" field.
func RetailerGT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGT(FieldRetailer, v))
}

// RetailerGTE applies the GTE predicate on the "retailer" field.
func RetailerGTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGTE(FieldRetailer, v))
}

// RetailerLT applies the LT predicate on the "retailer" field.
func RetailerLT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLT(FieldRetailer, v))
}

// RetailerLTE applies the LTE predicate on the "retailer" field.
func RetailerLTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLTE(FieldRetailer, v))
}

// RetailerContains applies the Contains predicate on the "retailer" field.
func RetailerContains(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContains(FieldRetailer, v))
}

// RetailerHasPrefix applies the HasPrefix predicate on the "retailer" field.
func RetailerHasPrefix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasPrefix(FieldRetailer, v))
}

// RetailerHasSuffix applies the HasSuffix predicate on the "retailer" field.
func RetailerHasSuffix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasSuffix(FieldRetailer, v))
}

// RetailerEqualFold applies the EqualFold predicate on the "retailer" field.
func RetailerEqualFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEqualFold(FieldRetailer, v))
}

// RetailerContainsFold applies the ContainsFold predicate on the "retailer" field.
func RetailerContainsFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContainsFold(FieldRetailer, v))
}

// PurchaseDateEQ applies the EQ predicate on the "purchase_date" field.
func PurchaseDateEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldPurchaseDate, v))
}

// PurchaseDateNEQ applies the NEQ predicate on the "purchase_date" field.
func PurchaseDateNEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNEQ(FieldPurchaseDate, v))
}

// PurchaseDateIn applies the In predicate on the "purchase_date" field.
func PurchaseDateIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldIn(FieldPurchaseDate, vs...))
}

// PurchaseDateNotIn applies the NotIn predicate on the "purchase_date" field.
func PurchaseDateNotIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNotIn(FieldPurchaseDate, vs...))
}

// PurchaseDateGT applies the GT predicate on the "purchase_date" field.
func PurchaseDateGT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGT(FieldPurchaseDate, v))
}

// PurchaseDateGTE applies the GTE predicate on the "purchase_date" field.
func PurchaseDateGTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGTE(FieldPurchaseDate, v))
}

// PurchaseDateLT applies the LT predicate on the "purchase_date" field.
func PurchaseDateLT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLT(FieldPurchaseDate, v))
}

// PurchaseDateLTE applies the LTE predicate on the "purchase_date" field.
func PurchaseDateLTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLTE(FieldPurchaseDate, v))
}

// PurchaseDateContains applies the Contains predicate on the "purchase_date" field.
func PurchaseDateContains(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContains(FieldPurchaseDate, v))
}

// PurchaseDateHasPrefix applies the HasPrefix predicate on the "purchase_date" field.
func PurchaseDateHasPrefix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasPrefix(FieldPurchaseDate, v))
}

// PurchaseDateHasSuffix applies the HasSuffix predicate on the "purchase_date" field.
func PurchaseDateHasSuffix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasSuffix(FieldPurchaseDate, v))
}

// PurchaseDateEqualFold applies the EqualFold predicate on the "purchase_date" field.
func PurchaseDateEqualFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEqualFold(FieldPurchaseDate, v))
}

// PurchaseDateContainsFold applies the ContainsFold predicate on the "purchase_date" field.
func PurchaseDateContainsFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContainsFold(FieldPurchaseDate, v))
}

// PurchaseTimeEQ applies the EQ predicate on the "purchase_time" field.
func PurchaseTimeEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldPurchaseTime, v))
}

// PurchaseTimeNEQ applies the NEQ predicate on the "purchase_time" field.
func PurchaseTimeNEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNEQ(FieldPurchaseTime, v))
}

// PurchaseTimeIn applies the In predicate on the "purchase_time" field.
func PurchaseTimeIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldIn(FieldPurchaseTime, vs...))
}

// PurchaseTimeNotIn applies the NotIn predicate on the "purchase_time" field.
func PurchaseTimeNotIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNotIn(FieldPurchaseTime, vs...))
}

// PurchaseTimeGT applies the GT predicate on the "purchase_time" field.
func PurchaseTimeGT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGT(FieldPurchaseTime, v))
}

// PurchaseTimeGTE applies the GTE predicate on the "purchase_time" field.
func PurchaseTimeGTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGTE(FieldPurchaseTime, v))
}

// PurchaseTimeLT applies the LT predicate on the "purchase_time" field.
func PurchaseTimeLT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLT(FieldPurchaseTime, v))
}

// PurchaseTimeLTE applies the LTE predicate on the "purchase_time" field.
func PurchaseTimeLTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLTE(FieldPurchaseTime, v))
}

// PurchaseTimeContains applies the Contains predicate on the "purchase_time" field.
func PurchaseTimeContains(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContains(FieldPurchaseTime, v))
}

// PurchaseTimeHasPrefix applies the HasPrefix predicate on the "purchase_time" field.
func PurchaseTimeHasPrefix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasPrefix(FieldPurchaseTime, v))
}

// PurchaseTimeHasSuffix applies the HasSuffix predicate on the "purchase_time" field.
func PurchaseTimeHasSuffix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasSuffix(FieldPurchaseTime, v))
}

// PurchaseTimeEqualFold applies the EqualFold predicate on the "purchase_time" field.
func PurchaseTimeEqualFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEqualFold(FieldPurchaseTime, v))
}

// PurchaseTimeContainsFold applies the ContainsFold predicate on the "purchase_time" field.
func PurchaseTimeContainsFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContainsFold(FieldPurchaseTime, v))
}

// TotalEQ applies the EQ predicate on the "total" field.
func TotalEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEQ(FieldTotal, v))
}

// TotalNEQ applies the NEQ predicate on the "total" field.
func TotalNEQ(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNEQ(FieldTotal, v))
}

// TotalIn applies the In predicate on the "total" field.
func TotalIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldIn(FieldTotal, vs...))
}

// TotalNotIn applies the NotIn predicate on the "total" field.
func TotalNotIn(vs ...string) predicate.Receipt {
	return predicate.Receipt(sql.FieldNotIn(FieldTotal, vs...))
}

// TotalGT applies the GT predicate on the "total" field.
func TotalGT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGT(FieldTotal, v))
}

// TotalGTE applies the GTE predicate on the "total" field.
func TotalGTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldGTE(FieldTotal, v))
}

// TotalLT applies the LT predicate on the "total" field.
func TotalLT(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLT(FieldTotal, v))
}

// TotalLTE applies the LTE predicate on the "total" field.
func TotalLTE(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldLTE(FieldTotal, v))
}

// TotalContains applies the Contains predicate on the "total" field.
func TotalContains(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContains(FieldTotal, v))
}

// TotalHasPrefix applies the HasPrefix predicate on the "total" field.
func TotalHasPrefix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasPrefix(FieldTotal, v))
}

// TotalHasSuffix applies the HasSuffix predicate on the "total" field.
func TotalHasSuffix(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldHasSuffix(FieldTotal, v))
}

// TotalEqualFold applies the EqualFold predicate on the "total" field.
func TotalEqualFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldEqualFold(FieldTotal, v))
}

// TotalContainsFold applies the ContainsFold predicate on the "total" field.
func TotalContainsFold(v string) predicate.Receipt {
	return predicate.Receipt(sql.FieldContainsFold(FieldTotal, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Receipt {
	return predicate.Receipt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.Item) predicate.Receipt {
	return predicate.Receipt(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Receipt) predicate.Receipt {
	return predicate.Receipt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Receipt) predicate.Receipt {
	return predicate.Receipt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Receipt) predicate.Receipt {
	return predicate.Receipt(sql.NotPredicates(p))
}
