// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "short_description", Type: field.TypeString},
		{Name: "price", Type: field.TypeInt},
		{Name: "receipt_items", Type: field.TypeInt, Nullable: true},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "items_receipts_items",
				Columns:    []*schema.Column{ItemsColumns[3]},
				RefColumns: []*schema.Column{ReceiptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ReceiptsColumns holds the columns for the "receipts" table.
	ReceiptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "retailer", Type: field.TypeString},
		{Name: "purchase_date", Type: field.TypeString},
		{Name: "purchase_time", Type: field.TypeString},
		{Name: "total", Type: field.TypeInt},
		{Name: "points", Type: field.TypeInt, Default: 0},
	}
	// ReceiptsTable holds the schema information for the "receipts" table.
	ReceiptsTable = &schema.Table{
		Name:       "receipts",
		Columns:    ReceiptsColumns,
		PrimaryKey: []*schema.Column{ReceiptsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemsTable,
		ReceiptsTable,
	}
)

func init() {
	ItemsTable.ForeignKeys[0].RefTable = ReceiptsTable
	ItemsTable.Annotation = &entsql.Annotation{
		Table: "items",
	}
	ReceiptsTable.Annotation = &entsql.Annotation{
		Table: "receipts",
	}
}
