// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ItemColumns holds the columns for the "item" table.
	ItemColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "short_description", Type: field.TypeString},
		{Name: "price", Type: field.TypeString},
		{Name: "receipt_items", Type: field.TypeInt, Nullable: true},
	}
	// ItemTable holds the schema information for the "item" table.
	ItemTable = &schema.Table{
		Name:       "item",
		Columns:    ItemColumns,
		PrimaryKey: []*schema.Column{ItemColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "item_receipt_items",
				Columns:    []*schema.Column{ItemColumns[3]},
				RefColumns: []*schema.Column{ReceiptColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ReceiptColumns holds the columns for the "receipt" table.
	ReceiptColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "retailer", Type: field.TypeString},
		{Name: "purchase_date", Type: field.TypeString},
		{Name: "purchase_time", Type: field.TypeString},
		{Name: "total", Type: field.TypeString},
	}
	// ReceiptTable holds the schema information for the "receipt" table.
	ReceiptTable = &schema.Table{
		Name:       "receipt",
		Columns:    ReceiptColumns,
		PrimaryKey: []*schema.Column{ReceiptColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemTable,
		ReceiptTable,
	}
)

func init() {
	ItemTable.ForeignKeys[0].RefTable = ReceiptTable
	ItemTable.Annotation = &entsql.Annotation{
		Table: "item",
	}
	ReceiptTable.Annotation = &entsql.Annotation{
		Table: "receipt",
	}
}
