// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"receipt-processor/ent/item"
	"receipt-processor/ent/predicate"
	"receipt-processor/ent/receipt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReceiptUpdate is the builder for updating Receipt entities.
type ReceiptUpdate struct {
	config
	hooks    []Hook
	mutation *ReceiptMutation
}

// Where appends a list predicates to the ReceiptUpdate builder.
func (ru *ReceiptUpdate) Where(ps ...predicate.Receipt) *ReceiptUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRetailer sets the "retailer" field.
func (ru *ReceiptUpdate) SetRetailer(s string) *ReceiptUpdate {
	ru.mutation.SetRetailer(s)
	return ru
}

// SetNillableRetailer sets the "retailer" field if the given value is not nil.
func (ru *ReceiptUpdate) SetNillableRetailer(s *string) *ReceiptUpdate {
	if s != nil {
		ru.SetRetailer(*s)
	}
	return ru
}

// SetPurchaseDate sets the "purchase_date" field.
func (ru *ReceiptUpdate) SetPurchaseDate(s string) *ReceiptUpdate {
	ru.mutation.SetPurchaseDate(s)
	return ru
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (ru *ReceiptUpdate) SetNillablePurchaseDate(s *string) *ReceiptUpdate {
	if s != nil {
		ru.SetPurchaseDate(*s)
	}
	return ru
}

// SetPurchaseTime sets the "purchase_time" field.
func (ru *ReceiptUpdate) SetPurchaseTime(s string) *ReceiptUpdate {
	ru.mutation.SetPurchaseTime(s)
	return ru
}

// SetNillablePurchaseTime sets the "purchase_time" field if the given value is not nil.
func (ru *ReceiptUpdate) SetNillablePurchaseTime(s *string) *ReceiptUpdate {
	if s != nil {
		ru.SetPurchaseTime(*s)
	}
	return ru
}

// SetTotal sets the "total" field.
func (ru *ReceiptUpdate) SetTotal(s string) *ReceiptUpdate {
	ru.mutation.SetTotal(s)
	return ru
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (ru *ReceiptUpdate) SetNillableTotal(s *string) *ReceiptUpdate {
	if s != nil {
		ru.SetTotal(*s)
	}
	return ru
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (ru *ReceiptUpdate) AddItemIDs(ids ...int) *ReceiptUpdate {
	ru.mutation.AddItemIDs(ids...)
	return ru
}

// AddItems adds the "items" edges to the Item entity.
func (ru *ReceiptUpdate) AddItems(i ...*Item) *ReceiptUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ru.AddItemIDs(ids...)
}

// Mutation returns the ReceiptMutation object of the builder.
func (ru *ReceiptUpdate) Mutation() *ReceiptMutation {
	return ru.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (ru *ReceiptUpdate) ClearItems() *ReceiptUpdate {
	ru.mutation.ClearItems()
	return ru
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (ru *ReceiptUpdate) RemoveItemIDs(ids ...int) *ReceiptUpdate {
	ru.mutation.RemoveItemIDs(ids...)
	return ru
}

// RemoveItems removes "items" edges to Item entities.
func (ru *ReceiptUpdate) RemoveItems(i ...*Item) *ReceiptUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ru.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReceiptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReceiptUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReceiptUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReceiptUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *ReceiptUpdate) check() error {
	if v, ok := ru.mutation.Retailer(); ok {
		if err := receipt.RetailerValidator(v); err != nil {
			return &ValidationError{Name: "retailer", err: fmt.Errorf(`ent: validator failed for field "Receipt.retailer": %w`, err)}
		}
	}
	if v, ok := ru.mutation.PurchaseDate(); ok {
		if err := receipt.PurchaseDateValidator(v); err != nil {
			return &ValidationError{Name: "purchase_date", err: fmt.Errorf(`ent: validator failed for field "Receipt.purchase_date": %w`, err)}
		}
	}
	if v, ok := ru.mutation.PurchaseTime(); ok {
		if err := receipt.PurchaseTimeValidator(v); err != nil {
			return &ValidationError{Name: "purchase_time", err: fmt.Errorf(`ent: validator failed for field "Receipt.purchase_time": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Total(); ok {
		if err := receipt.TotalValidator(v); err != nil {
			return &ValidationError{Name: "total", err: fmt.Errorf(`ent: validator failed for field "Receipt.total": %w`, err)}
		}
	}
	return nil
}

func (ru *ReceiptUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(receipt.Table, receipt.Columns, sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Retailer(); ok {
		_spec.SetField(receipt.FieldRetailer, field.TypeString, value)
	}
	if value, ok := ru.mutation.PurchaseDate(); ok {
		_spec.SetField(receipt.FieldPurchaseDate, field.TypeString, value)
	}
	if value, ok := ru.mutation.PurchaseTime(); ok {
		_spec.SetField(receipt.FieldPurchaseTime, field.TypeString, value)
	}
	if value, ok := ru.mutation.Total(); ok {
		_spec.SetField(receipt.FieldTotal, field.TypeString, value)
	}
	if ru.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedItemsIDs(); len(nodes) > 0 && !ru.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{receipt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReceiptUpdateOne is the builder for updating a single Receipt entity.
type ReceiptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReceiptMutation
}

// SetRetailer sets the "retailer" field.
func (ruo *ReceiptUpdateOne) SetRetailer(s string) *ReceiptUpdateOne {
	ruo.mutation.SetRetailer(s)
	return ruo
}

// SetNillableRetailer sets the "retailer" field if the given value is not nil.
func (ruo *ReceiptUpdateOne) SetNillableRetailer(s *string) *ReceiptUpdateOne {
	if s != nil {
		ruo.SetRetailer(*s)
	}
	return ruo
}

// SetPurchaseDate sets the "purchase_date" field.
func (ruo *ReceiptUpdateOne) SetPurchaseDate(s string) *ReceiptUpdateOne {
	ruo.mutation.SetPurchaseDate(s)
	return ruo
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (ruo *ReceiptUpdateOne) SetNillablePurchaseDate(s *string) *ReceiptUpdateOne {
	if s != nil {
		ruo.SetPurchaseDate(*s)
	}
	return ruo
}

// SetPurchaseTime sets the "purchase_time" field.
func (ruo *ReceiptUpdateOne) SetPurchaseTime(s string) *ReceiptUpdateOne {
	ruo.mutation.SetPurchaseTime(s)
	return ruo
}

// SetNillablePurchaseTime sets the "purchase_time" field if the given value is not nil.
func (ruo *ReceiptUpdateOne) SetNillablePurchaseTime(s *string) *ReceiptUpdateOne {
	if s != nil {
		ruo.SetPurchaseTime(*s)
	}
	return ruo
}

// SetTotal sets the "total" field.
func (ruo *ReceiptUpdateOne) SetTotal(s string) *ReceiptUpdateOne {
	ruo.mutation.SetTotal(s)
	return ruo
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (ruo *ReceiptUpdateOne) SetNillableTotal(s *string) *ReceiptUpdateOne {
	if s != nil {
		ruo.SetTotal(*s)
	}
	return ruo
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (ruo *ReceiptUpdateOne) AddItemIDs(ids ...int) *ReceiptUpdateOne {
	ruo.mutation.AddItemIDs(ids...)
	return ruo
}

// AddItems adds the "items" edges to the Item entity.
func (ruo *ReceiptUpdateOne) AddItems(i ...*Item) *ReceiptUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ruo.AddItemIDs(ids...)
}

// Mutation returns the ReceiptMutation object of the builder.
func (ruo *ReceiptUpdateOne) Mutation() *ReceiptMutation {
	return ruo.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (ruo *ReceiptUpdateOne) ClearItems() *ReceiptUpdateOne {
	ruo.mutation.ClearItems()
	return ruo
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (ruo *ReceiptUpdateOne) RemoveItemIDs(ids ...int) *ReceiptUpdateOne {
	ruo.mutation.RemoveItemIDs(ids...)
	return ruo
}

// RemoveItems removes "items" edges to Item entities.
func (ruo *ReceiptUpdateOne) RemoveItems(i ...*Item) *ReceiptUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ruo.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the ReceiptUpdate builder.
func (ruo *ReceiptUpdateOne) Where(ps ...predicate.Receipt) *ReceiptUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReceiptUpdateOne) Select(field string, fields ...string) *ReceiptUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Receipt entity.
func (ruo *ReceiptUpdateOne) Save(ctx context.Context) (*Receipt, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReceiptUpdateOne) SaveX(ctx context.Context) *Receipt {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReceiptUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReceiptUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *ReceiptUpdateOne) check() error {
	if v, ok := ruo.mutation.Retailer(); ok {
		if err := receipt.RetailerValidator(v); err != nil {
			return &ValidationError{Name: "retailer", err: fmt.Errorf(`ent: validator failed for field "Receipt.retailer": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.PurchaseDate(); ok {
		if err := receipt.PurchaseDateValidator(v); err != nil {
			return &ValidationError{Name: "purchase_date", err: fmt.Errorf(`ent: validator failed for field "Receipt.purchase_date": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.PurchaseTime(); ok {
		if err := receipt.PurchaseTimeValidator(v); err != nil {
			return &ValidationError{Name: "purchase_time", err: fmt.Errorf(`ent: validator failed for field "Receipt.purchase_time": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Total(); ok {
		if err := receipt.TotalValidator(v); err != nil {
			return &ValidationError{Name: "total", err: fmt.Errorf(`ent: validator failed for field "Receipt.total": %w`, err)}
		}
	}
	return nil
}

func (ruo *ReceiptUpdateOne) sqlSave(ctx context.Context) (_node *Receipt, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(receipt.Table, receipt.Columns, sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Receipt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, receipt.FieldID)
		for _, f := range fields {
			if !receipt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != receipt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Retailer(); ok {
		_spec.SetField(receipt.FieldRetailer, field.TypeString, value)
	}
	if value, ok := ruo.mutation.PurchaseDate(); ok {
		_spec.SetField(receipt.FieldPurchaseDate, field.TypeString, value)
	}
	if value, ok := ruo.mutation.PurchaseTime(); ok {
		_spec.SetField(receipt.FieldPurchaseTime, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Total(); ok {
		_spec.SetField(receipt.FieldTotal, field.TypeString, value)
	}
	if ruo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedItemsIDs(); len(nodes) > 0 && !ruo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Receipt{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{receipt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
