// Code generated by ent, DO NOT EDIT.

package ent

import (
	"receipt-processor/ent/item"
	"receipt-processor/ent/receipt"
	"receipt-processor/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescShortDescription is the schema descriptor for short_description field.
	itemDescShortDescription := itemFields[0].Descriptor()
	// item.ShortDescriptionValidator is a validator for the "short_description" field. It is called by the builders before save.
	item.ShortDescriptionValidator = itemDescShortDescription.Validators[0].(func(string) error)
	// itemDescPrice is the schema descriptor for price field.
	itemDescPrice := itemFields[1].Descriptor()
	// item.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	item.PriceValidator = itemDescPrice.Validators[0].(func(string) error)
	receiptFields := schema.Receipt{}.Fields()
	_ = receiptFields
	// receiptDescRetailer is the schema descriptor for retailer field.
	receiptDescRetailer := receiptFields[0].Descriptor()
	// receipt.RetailerValidator is a validator for the "retailer" field. It is called by the builders before save.
	receipt.RetailerValidator = receiptDescRetailer.Validators[0].(func(string) error)
	// receiptDescPurchaseDate is the schema descriptor for purchase_date field.
	receiptDescPurchaseDate := receiptFields[1].Descriptor()
	// receipt.PurchaseDateValidator is a validator for the "purchase_date" field. It is called by the builders before save.
	receipt.PurchaseDateValidator = receiptDescPurchaseDate.Validators[0].(func(string) error)
	// receiptDescPurchaseTime is the schema descriptor for purchase_time field.
	receiptDescPurchaseTime := receiptFields[2].Descriptor()
	// receipt.PurchaseTimeValidator is a validator for the "purchase_time" field. It is called by the builders before save.
	receipt.PurchaseTimeValidator = receiptDescPurchaseTime.Validators[0].(func(string) error)
	// receiptDescTotal is the schema descriptor for total field.
	receiptDescTotal := receiptFields[3].Descriptor()
	// receipt.TotalValidator is a validator for the "total" field. It is called by the builders before save.
	receipt.TotalValidator = receiptDescTotal.Validators[0].(func(string) error)
}
