// Code generated by ent, DO NOT EDIT.

package ent

import (
	"billing/internal/db/ent/receipt"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Receipt is the model entity for the Receipt schema.
type Receipt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Retailer holds the value of the "retailer" field.
	Retailer string `json:"retailer,omitempty"`
	// PurchaseDate holds the value of the "purchase_date" field.
	PurchaseDate string `json:"purchase_date,omitempty"`
	// PurchaseTime holds the value of the "purchase_time" field.
	PurchaseTime string `json:"purchase_time,omitempty"`
	// Total holds the value of the "total" field.
	Total string `json:"total,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReceiptQuery when eager-loading is set.
	Edges        ReceiptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReceiptEdges holds the relations/edges for other nodes in the graph.
type ReceiptEdges struct {
	// Items holds the value of the items edge.
	Items []*Item `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e ReceiptEdges) ItemsOrErr() ([]*Item, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Receipt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case receipt.FieldID:
			values[i] = new(sql.NullInt64)
		case receipt.FieldRetailer, receipt.FieldPurchaseDate, receipt.FieldPurchaseTime, receipt.FieldTotal:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Receipt fields.
func (r *Receipt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case receipt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case receipt.FieldRetailer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field retailer", values[i])
			} else if value.Valid {
				r.Retailer = value.String
			}
		case receipt.FieldPurchaseDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_date", values[i])
			} else if value.Valid {
				r.PurchaseDate = value.String
			}
		case receipt.FieldPurchaseTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_time", values[i])
			} else if value.Valid {
				r.PurchaseTime = value.String
			}
		case receipt.FieldTotal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value.Valid {
				r.Total = value.String
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Receipt.
// This includes values selected through modifiers, order, etc.
func (r *Receipt) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the Receipt entity.
func (r *Receipt) QueryItems() *ItemQuery {
	return NewReceiptClient(r.config).QueryItems(r)
}

// Update returns a builder for updating this Receipt.
// Note that you need to call Receipt.Unwrap() before calling this method if this Receipt
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Receipt) Update() *ReceiptUpdateOne {
	return NewReceiptClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Receipt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Receipt) Unwrap() *Receipt {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Receipt is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Receipt) String() string {
	var builder strings.Builder
	builder.WriteString("Receipt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("retailer=")
	builder.WriteString(r.Retailer)
	builder.WriteString(", ")
	builder.WriteString("purchase_date=")
	builder.WriteString(r.PurchaseDate)
	builder.WriteString(", ")
	builder.WriteString("purchase_time=")
	builder.WriteString(r.PurchaseTime)
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(r.Total)
	builder.WriteByte(')')
	return builder.String()
}

// Receipts is a parsable slice of Receipt.
type Receipts []*Receipt
