// Code generated by ent, DO NOT EDIT.

package ent

import (
	"billing/internal/db/ent/item"
	"billing/internal/db/ent/receipt"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReceiptCreate is the builder for creating a Receipt entity.
type ReceiptCreate struct {
	config
	mutation *ReceiptMutation
	hooks    []Hook
}

// SetRetailer sets the "retailer" field.
func (rc *ReceiptCreate) SetRetailer(s string) *ReceiptCreate {
	rc.mutation.SetRetailer(s)
	return rc
}

// SetPurchaseDate sets the "purchase_date" field.
func (rc *ReceiptCreate) SetPurchaseDate(s string) *ReceiptCreate {
	rc.mutation.SetPurchaseDate(s)
	return rc
}

// SetPurchaseTime sets the "purchase_time" field.
func (rc *ReceiptCreate) SetPurchaseTime(s string) *ReceiptCreate {
	rc.mutation.SetPurchaseTime(s)
	return rc
}

// SetTotal sets the "total" field.
func (rc *ReceiptCreate) SetTotal(s string) *ReceiptCreate {
	rc.mutation.SetTotal(s)
	return rc
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (rc *ReceiptCreate) AddItemIDs(ids ...int) *ReceiptCreate {
	rc.mutation.AddItemIDs(ids...)
	return rc
}

// AddItems adds the "items" edges to the Item entity.
func (rc *ReceiptCreate) AddItems(i ...*Item) *ReceiptCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return rc.AddItemIDs(ids...)
}

// Mutation returns the ReceiptMutation object of the builder.
func (rc *ReceiptCreate) Mutation() *ReceiptMutation {
	return rc.mutation
}

// Save creates the Receipt in the database.
func (rc *ReceiptCreate) Save(ctx context.Context) (*Receipt, error) {
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReceiptCreate) SaveX(ctx context.Context) *Receipt {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReceiptCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReceiptCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReceiptCreate) check() error {
	if _, ok := rc.mutation.Retailer(); !ok {
		return &ValidationError{Name: "retailer", err: errors.New(`ent: missing required field "Receipt.retailer"`)}
	}
	if v, ok := rc.mutation.Retailer(); ok {
		if err := receipt.RetailerValidator(v); err != nil {
			return &ValidationError{Name: "retailer", err: fmt.Errorf(`ent: validator failed for field "Receipt.retailer": %w`, err)}
		}
	}
	if _, ok := rc.mutation.PurchaseDate(); !ok {
		return &ValidationError{Name: "purchase_date", err: errors.New(`ent: missing required field "Receipt.purchase_date"`)}
	}
	if v, ok := rc.mutation.PurchaseDate(); ok {
		if err := receipt.PurchaseDateValidator(v); err != nil {
			return &ValidationError{Name: "purchase_date", err: fmt.Errorf(`ent: validator failed for field "Receipt.purchase_date": %w`, err)}
		}
	}
	if _, ok := rc.mutation.PurchaseTime(); !ok {
		return &ValidationError{Name: "purchase_time", err: errors.New(`ent: missing required field "Receipt.purchase_time"`)}
	}
	if v, ok := rc.mutation.PurchaseTime(); ok {
		if err := receipt.PurchaseTimeValidator(v); err != nil {
			return &ValidationError{Name: "purchase_time", err: fmt.Errorf(`ent: validator failed for field "Receipt.purchase_time": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "Receipt.total"`)}
	}
	if v, ok := rc.mutation.Total(); ok {
		if err := receipt.TotalValidator(v); err != nil {
			return &ValidationError{Name: "total", err: fmt.Errorf(`ent: validator failed for field "Receipt.total": %w`, err)}
		}
	}
	return nil
}

func (rc *ReceiptCreate) sqlSave(ctx context.Context) (*Receipt, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ReceiptCreate) createSpec() (*Receipt, *sqlgraph.CreateSpec) {
	var (
		_node = &Receipt{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(receipt.Table, sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.Retailer(); ok {
		_spec.SetField(receipt.FieldRetailer, field.TypeString, value)
		_node.Retailer = value
	}
	if value, ok := rc.mutation.PurchaseDate(); ok {
		_spec.SetField(receipt.FieldPurchaseDate, field.TypeString, value)
		_node.PurchaseDate = value
	}
	if value, ok := rc.mutation.PurchaseTime(); ok {
		_spec.SetField(receipt.FieldPurchaseTime, field.TypeString, value)
		_node.PurchaseTime = value
	}
	if value, ok := rc.mutation.Total(); ok {
		_spec.SetField(receipt.FieldTotal, field.TypeString, value)
		_node.Total = value
	}
	if nodes := rc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   receipt.ItemsTable,
			Columns: []string{receipt.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReceiptCreateBulk is the builder for creating many Receipt entities in bulk.
type ReceiptCreateBulk struct {
	config
	err      error
	builders []*ReceiptCreate
}

// Save creates the Receipt entities in the database.
func (rcb *ReceiptCreateBulk) Save(ctx context.Context) ([]*Receipt, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Receipt, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReceiptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReceiptCreateBulk) SaveX(ctx context.Context) []*Receipt {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReceiptCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReceiptCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
